layout_spectrum: 0.2758688449393958
typography_spectrum: 0.09212521626614034
color:
  brandStrength: 0.9509969761129469
  lightness: 0.3528473142068833
  saturation: 0.04325343621894717
  rhythmicContrast: 0.7757414900697768
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: www.jamesvaulkhard.com
